apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: arm64v8/mysql:8-oracle
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "lab6_bd"
        - name: MYSQL_ROOT_PASSWORD
          value: "0000"
